# Generated by Django 5.2.6 on 2025-09-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('sobremesa', 'Sobremesa'), ('drink', 'Drink')], default='comida', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredients',
            field=models.TextField(verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='instructions',
            field=models.TextField(verbose_name='Modo de preparo'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
